tasks:
  - init: start xml-parser
    command: npm xml-parser

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - ritwickdey.liveserver@5.6.1:5Mhl1RgVVDcIym163x8r+w==